# Generated by Django 2.2.6 on 2024-03-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220106_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_images',
            name='Input_image',
            field=models.FileField(upload_to='static/images/'),
        ),
    ]
